### ISSUE TITLE
chunk error when adding enable3d to starter phaser 3 project repository

### ISSUE THREAD

**Issue by prolightHub** [yandeu/enable3d#2]
The error:
https://cdn.discordapp.com/attachments/416623653741133837/677758803193626637/Annotation_2020-02-13_231055.png

I'm following this error:
https://www.youtube.com/watch?v=AHQEWontFfU&feature=youtu.be

**Comment by yandeu** [comment]
I see. I guess I know what the issue is. 
I will fix it this weekend.

**Comment by prolightHub** [comment]
Sounds good! I can't wait to use this!

**Comment by yandeu** [comment]
I fixed it in version 14.

And I added a [enable3d-project-template](https://github.com/yandeu/enable3d-project-template), which is a clone of the phaser-project-template.

_Btw. I will implement a Kinematic Character Controller in the next release. Just so that you know to not waste much time of a good custom implementation :)_

**Comment by prolightHub** [comment]
Sounds good!
